package repository

import (
	"context"

	"github.com/daniel-caso-github/realtime-alerting-system/internal/domain/entity"
	"github.com/daniel-caso-github/realtime-alerting-system/internal/domain/valueobject"
)

// AlertRepository defines the persistence operations for alerts.
type AlertRepository interface {
	// Create saves a new alert.
	Create(ctx context.Context, alert *entity.Alert) error

	// GetByID finds an alert by its ID.
	// Returns ErrNotFound if it doesn't exist.
	GetByID(ctx context.Context, id entity.ID) (*entity.Alert, error)

	// Update updates an existing alert.
	// Returns ErrNotFound if it doesn't exist.
	Update(ctx context.Context, alert *entity.Alert) error

	// Delete removes an alert by its ID.
	// Returns ErrNotFound if it doesn't exist.
	Delete(ctx context.Context, id entity.ID) error

	// List returns paginated alerts with optional filters.
	List(ctx context.Context, filter valueobject.AlertFilter, pagination valueobject.Pagination) (*valueobject.PaginatedResult[*entity.Alert], error)

	// ListByStatus returns alerts filtered by status.
	ListByStatus(ctx context.Context, status entity.AlertStatus, pagination valueobject.Pagination) (*valueobject.PaginatedResult[*entity.Alert], error)

	// ListByRuleID returns alerts generated by a specific rule.
	ListByRuleID(ctx context.Context, ruleID entity.ID, pagination valueobject.Pagination) (*valueobject.PaginatedResult[*entity.Alert], error)

	// ListActive returns all active alerts (unpaginated, for broadcasting).
	ListActive(ctx context.Context) ([]*entity.Alert, error)

	// ListExpired returns alerts that have expired but are still active.
	// Useful for a cleanup job to mark them as expired.
	ListExpired(ctx context.Context) ([]*entity.Alert, error)

	// Count returns the total number of alerts.
	Count(ctx context.Context) (int64, error)

	// CountByStatus returns the number of alerts by status.
	CountByStatus(ctx context.Context, status entity.AlertStatus) (int64, error)

	// CountBySeverity returns the number of alerts by severity.
	CountBySeverity(ctx context.Context, severity entity.AlertSeverity) (int64, error)

	// GetStatistics returns aggregated alert statistics.
	GetStatistics(ctx context.Context) (*AlertStatistics, error)
}

// AlertStatistics contains aggregated alert statistics.
type AlertStatistics struct {
	TotalAlerts        int64            `json:"total_alerts" db:"total_alerts"`
	ActiveAlerts       int64            `json:"active_alerts" db:"active_alerts"`
	AcknowledgedAlerts int64            `json:"acknowledged_alerts" db:"acknowledged_alerts"`
	ResolvedAlerts     int64            `json:"resolved_alerts" db:"resolved_alerts"`
	BySeverity         map[string]int64 `json:"by_severity"`
	BySource           map[string]int64 `json:"by_source"`
}
