codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mocks/**"
  - "cmd/**"
  - "deployments/**"
  - "migrations/**"
  - "docs/**"

flags:
  unittests:
    paths:
      - internal/
    carryforward: true
